### ISSUE TITLE
HTTP authentication

### ISSUE THREAD

**Issue by pgbezerra** [essuraj/elasticsearch-toolbox#10]
First of all, thank you for the tool, it's great!

When using search guard, for example, is not possible to use the elasticsearch-toolbox because it seems that is not available to authenticate with basic HTTP.
Would be very nice to have this feature.
Thank you!

**Comment by pgbezerra** [comment]
If we write the URL with user and password, it works.
Sorry.

**Comment by yohan-shanaka** [comment]
yes, its working thanks
